{"error": null, "issues": [{"address": 812, "code": "ire(tokens_buy > 0);\n\n      ", "debug": "The exception is triggered under the following conditions:\n\nstorage_3: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_Delta_0: 0x2fb0c5c00000000000000000000000000000000000000000000000000000000\ncalldatasize_Delta: 0x4\nstorage_4: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/data/demo_analysis/source_code/0x9d06cbafa865037a01d322d3f4222fa3e04e5488.sol", "function": "fallback", "lineno": 46, "title": "Exception state", "type": "Informational"}, {"address": 1220, "code": "s,uint256)\")),owner, msg.sender,tokens_buy)){\n        \treturn false;\n        }\n\n        ui", "debug": "", "description": "This contract executes a message call to to another contract. Make sure that the called contract is trusted and does not execute user-supplied code.", "filename": "/data/demo_analysis/source_code/0x9d06cbafa865037a01d322d3f4222fa3e04e5488.sol", "function": "fallback", "lineno": 48, "title": "Message call to external contract", "type": "Informational"}, {"address": 1220, "code": "s,uint256)\")),owner, msg.sender,tokens_buy)){\n        \treturn false;\n        }\n\n        ui", "debug": "", "description": "Multiple sends exist in one transaction, try to isolate each external call into its own transaction. As external calls can fail accidentally or deliberately.\nConsecutive calls: \nCall at address: 1339\n", "filename": "/data/demo_analysis/source_code/0x9d06cbafa865037a01d322d3f4222fa3e04e5488.sol", "function": "fallback", "lineno": 48, "title": "Multiple Calls", "type": "Information"}, {"address": 1339, "code": "\n\n      //Withdra", "debug": "", "description": "The return value of an external call is not checked. Note that execution continue even if the called contract throws.", "filename": "/data/demo_analysis/source_code/0x9d06cbafa865037a01d322d3f4222fa3e04e5488.sol", "function": "fallback", "lineno": 57, "title": "Unchecked CALL return value", "type": "Informational"}, {"address": 1687, "code": "nge token\n      fun", "debug": "", "description": "The return value of an external call is not checked. Note that execution continue even if the called contract throws.", "filename": "/data/demo_analysis/source_code/0x9d06cbafa865037a01d322d3f4222fa3e04e5488.sol", "function": "withdraw(uint256)", "lineno": 69, "title": "Unchecked CALL return value", "type": "Informational"}], "success": true}